#ifndef GAME_DEFINITIONS_H
#define GAME_DEFINITIONS_H

#include "definitions/ClassAndRaceDefinitions.h"

#define ATTACK_ZONE_WIDTH 30
#define ATTACK_ZONE_HEIGHT 30
#define ATTACK_NPC_ZONE_WIDTH 50
#define ATTACK_NPC_ZONE_HEIGHT 50
#define MAX_RANGE_ZONE 800

// CRON ENVS
#define MIN_DISTANCE_NPC 200 // TODO -> MOVE TO DEFINITIONS
#define MIN_DISTANCE_TO_ATTACK_PLAYER 100
#define SPEED 10
#define SPEED_NPC 5
#define RESPAWN_TIME_NPC 10

// INIT NPC DEFINITIONS
#define NPC_RANDOM_DROP 0.2
#define NPC_INIT_HEALTH_POINTS 100
#define NPC_INIT_SKILLS 10

// INIT PLAYER DEFINITIONS
#define PLAYER_INITIAL_LEVEL 1

#endif
